mutation CreateUser($username: String!, $role: String!) @auth(level: PUBLIC) {
  user_insert(data: {username: $username, role: $role, createdAt_expr: "request.time"})
}

mutation LogTelemetry($deviceId: String!, $type: String!, $val: Float!) @auth(level: USER) {
  deviceTelemetry_insert(data: {deviceId: $deviceId, telemetryType: $type, value: $val, timestamp_expr: "request.time", userId_expr: "auth.uid"})
}

query GetMyDiagnosticReports @auth(level: USER) {
  diagnosticReports(where: {userId: {eq_expr: "auth.uid"}}) {
    summary
    status
    reportDate
    deviceTelemetry {
      deviceId
      value
    }
  }
}

mutation CreateSchematicRecord($name: String!, $vectorData: String!) @auth(level: USER) {
  motherboardSchematic_insert(data: {name: $name, vectorData: $vectorData, uploadDate_expr: "request.time", userId_expr: "auth.uid"})
}